#!/bin/bash

echo "Content-Type:text/html; charset=utf-8"
echo ""
echo "<html><head><title>$2</title>"
echo "<style>table,th,td { border:1px solid black; } th { background-color:#666666"
echo "color:#ffffff text-align:center font-weight:bold } </style>"
echo "</head><body>"
echo "<h1>Browsing Directory</h1>$2 in host machine<br/><br/>"
echo "<table><tr><th>File:</th></tr>"
ls "$1" -ap1 | gawk '{ print "<tr><td><a href=\""$1"\">"$1"</a><br/></td></tr>" }' | cat
echo "</table>"
echo "</body></html>"
