#!/bin/bash
#
# Usage: buscapids programa
#
###########################################################################
# TODO: verificar numero de parametros correcto.
###########################################################################
#
# Este script deve receber o nome de um programa e
# retornar os pids de todos os processos desse programa.
#
# O comando ps com a opcao -e devolve a listagem de todos os processos.
# O resultado deste comando e' redireccionado para o grep que selecciona
# apenas as linhas referentes aos processos do programa para o qual se
# pretende obter os pids. 
#
###########################################################################
# TODO: completar o script para fazer o pretendido.
###########################################################################
#
# Sugestao: consulte as paginas do man e utilize o comando cut ou awk
# para extrair do resultado apenas os pids dos processos. Utilize um pipe
# para  redireccionar o resultado obtido para o comando cut ou awk.
#
echo "Content-Type:text/html; charset=utf-8"
echo ""
echo "<html><head><title>$(pwd)</title></head><body>"
ls "$1" -ap1 | gawk '{ print "<a href=\""$1"\">"$1"</a><br/>" }' | cat
echo "</body></html>"
